"""
Forensic Report Generator: Generates comprehensive PDF reports with ReportLab
and complete machine-readable JSON exports.
"""
import io
import json
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Adds running headers, footers, and page numbers 'Page X of Y' to PDF."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Header
        self.drawString(40, 760, "SIH26106 | AI-POWERED EMAIL FORENSIC INTELLIGENCE PLATFORM")
        self.drawRightString(572, 760, "CONFIDENTIAL / SOC INVESTIGATION REPORT")
        self.setStrokeColor(colors.HexColor("#334155"))
        self.setLineWidth(0.5)
        self.line(40, 752, 572, 752)

        # Footer
        self.line(40, 42, 572, 42)
        self.setFont("Helvetica", 7.5)
        self.drawString(40, 30, "Generated by Automated Forensic Pipeline — Analyst Validation Required")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(572, 30, page_text)
        self.restoreState()


class ReportGenerator:
    """Produces PDF and JSON forensic investigation deliverables."""

    @staticmethod
    def generate_pdf(investigation_data: Dict[str, Any]) -> bytes:
        """Constructs a multi-page PDF forensic report using ReportLab."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=40,
            rightMargin=40,
            topMargin=55,
            bottomMargin=55
        )

        styles = getSampleStyleSheet()
        # Custom Dark/SOC Theme Styles
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=colors.HexColor("#0f172a")
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#475569")
        )
        h2_style = ParagraphStyle(
            "SectionH2",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#1e293b"),
            spaceBefore=12,
            spaceAfter=4
        )
        body_style = ParagraphStyle(
            "BodyTextCustom",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#334155")
        )
        code_style = ParagraphStyle(
            "CodeCustom",
            parent=styles["Normal"],
            fontName="Courier",
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor("#0f172a")
        )

        story = []

        summary = investigation_data.get("summary", {})
        auth = investigation_data.get("authentication", {})
        nlp = investigation_data.get("nlp_analysis", {})
        sub_scores = investigation_data.get("sub_scores", {})
        factors = investigation_data.get("threat_factors", [])
        urls = investigation_data.get("urls", [])
        attachments = investigation_data.get("attachments", [])
        hops = investigation_data.get("routing_hops", [])
        timeline = investigation_data.get("timeline", [])

        # 1. Header & Investigation Metadata
        story.append(Paragraph("EMAIL THREAT FORENSIC REPORT", title_style))
        story.append(Paragraph(f"Case Reference: <b>{summary.get('investigation_id', 'INV-UNKNOWN')}</b> | Generated: {summary.get('date', 'Unknown')}", subtitle_style))
        story.append(Spacer(1, 10))

        # Severity Banner
        threat_score = summary.get("overall_threat_score", 0)
        severity = summary.get("threat_level", "SAFE").upper()
        sev_color = colors.HexColor("#ef4444") if severity == "CRITICAL" else (
            colors.HexColor("#f97316") if severity == "HIGH" else (
                colors.HexColor("#f59e0b") if severity == "MEDIUM" else (
                    colors.HexColor("#3b82f6") if severity == "LOW" else colors.HexColor("#10b981")
                )
            )
        )

        sev_data = [
            [
                Paragraph(f"<b>OVERALL THREAT SCORE:</b> {threat_score} / 100", ParagraphStyle("Sev", parent=body_style, fontName="Helvetica-Bold", fontSize=11, textColor=colors.white)),
                Paragraph(f"<b>SEVERITY LEVEL:</b> {severity}", ParagraphStyle("Sev2", parent=body_style, fontName="Helvetica-Bold", fontSize=11, textColor=colors.white)),
                Paragraph(f"<b>HEADER TRUST:</b> {summary.get('header_trust_score', 100)} / 100", ParagraphStyle("Sev3", parent=body_style, fontName="Helvetica-Bold", fontSize=11, textColor=colors.white))
            ]
        ]
        sev_table = Table(sev_data, colWidths=[180, 172, 180])
        sev_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), sev_color),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(sev_table)
        story.append(Spacer(1, 12))

        # 2. Executive Summary & Email Metadata
        story.append(Paragraph("1. Incident Summary & Core Identifiers", h2_style))
        meta_table_data = [
            [Paragraph("<b>Subject:</b>", body_style), Paragraph(summary.get("subject", "(No Subject)"), body_style)],
            [Paragraph("<b>From (Sender):</b>", body_style), Paragraph(summary.get("sender", ""), body_style)],
            [Paragraph("<b>To (Recipient):</b>", body_style), Paragraph(summary.get("recipient", ""), body_style)],
            [Paragraph("<b>Transmission Date:</b>", body_style), Paragraph(summary.get("date", ""), body_style)],
            [Paragraph("<b>Forensic Verdict:</b>", body_style), Paragraph(summary.get("verdict", "Automated triage completed."), body_style)],
        ]
        meta_table = Table(meta_table_data, colWidths=[120, 412])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 12))

        # 3. Authentication Verification Table
        story.append(Paragraph("2. Email Authentication Protocol Findings", h2_style))
        spf = auth.get("spf", {})
        dkim = auth.get("dkim", {})
        dmarc = auth.get("dmarc", {})
        auth_data = [
            [Paragraph("<b>Protocol</b>", body_style), Paragraph("<b>Status</b>", body_style), Paragraph("<b>Forensic Evidence & Findings</b>", body_style)],
            [Paragraph("<b>SPF</b>", body_style), Paragraph(f"<b>{spf.get('status', 'None')}</b>", body_style), Paragraph(spf.get("evidence", ""), body_style)],
            [Paragraph("<b>DKIM</b>", body_style), Paragraph(f"<b>{dkim.get('status', 'None')}</b>", body_style), Paragraph(dkim.get("evidence", ""), body_style)],
            [Paragraph("<b>DMARC</b>", body_style), Paragraph(f"<b>{dmarc.get('status', 'None')}</b>", body_style), Paragraph(dmarc.get("evidence", ""), body_style)],
        ]
        auth_table = Table(auth_data, colWidths=[70, 70, 392])
        auth_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(auth_table)
        story.append(Spacer(1, 12))

        # 4. Itemized Explainable Threat Factors
        if factors:
            story.append(Paragraph("3. Explainable Threat Factors (Why This Email Was Flagged)", h2_style))
            factor_rows = [[Paragraph("<b>Points</b>", body_style), Paragraph("<b>Category</b>", body_style), Paragraph("<b>Trigger / Indicator</b>", body_style), Paragraph("<b>Evidence</b>", body_style)]]
            for f in factors:
                factor_rows.append([
                    Paragraph(f"<b>+{f.get('points', 0)}</b>", body_style),
                    Paragraph(f.get("category", ""), body_style),
                    Paragraph(f.get("factor", ""), body_style),
                    Paragraph(f.get("evidence", "")[:120], code_style),
                ])
            f_table = Table(factor_rows, colWidths=[50, 75, 160, 247])
            f_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#fee2e2")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(f_table)
            story.append(Spacer(1, 12))

        # 5. NLP & Social Engineering Analysis
        story.append(Paragraph("4. AI/NLP Social Engineering & Intent Analysis", h2_style))
        nlp_data = [
            [Paragraph("<b>Intent Classification:</b>", body_style), Paragraph(f"<b>{nlp.get('intent_label', 'Benign')}</b> (Phishing Probability: {int(nlp.get('phishing_probability', 0)*100)}%)", body_style)],
            [Paragraph("<b>Identified Categories:</b>", body_style), Paragraph(", ".join(nlp.get("categories", [])) or "None", body_style)],
            [Paragraph("<b>Suspicious Keywords:</b>", body_style), Paragraph(", ".join(nlp.get("suspicious_keywords", [])) or "None", body_style)],
            [Paragraph("<b>Key Evidence Snippets:</b>", body_style), Paragraph("; ".join(nlp.get("evidence_sentences", [])) or "No explicit social engineering patterns detected.", body_style)],
            [Paragraph("<b>Model Architecture:</b>", body_style), Paragraph(nlp.get("model_engine", "Heuristic Rule & TF-IDF Engine"), body_style)],
        ]
        nlp_table = Table(nlp_data, colWidths=[140, 392])
        nlp_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(nlp_table)
        story.append(Spacer(1, 12))

        # 6. Reconstructed Transmission Hops
        if hops:
            story.append(Paragraph("5. Reconstructed Network Routing Hops & Geo-Origin", h2_style))
            hop_rows = [[Paragraph("<b>Hop</b>", body_style), Paragraph("<b>Relay Host / IP</b>", body_style), Paragraph("<b>Type</b>", body_style), Paragraph("<b>Location</b>", body_style), Paragraph("<b>ISP / ASN</b>", body_style)]]
            for h in hops:
                loc = f"{h.get('city', 'Unknown')}, {h.get('country', 'Unknown')}"
                ip_val = h.get("from_ip") or h.get("by_ip") or "No IP"
                hop_rows.append([
                    Paragraph(f"<b>#{h.get('hop_number', 0)}</b>", body_style),
                    Paragraph(f"{h.get('from_hostname', '')}<br/><b>[{ip_val}]</b>", code_style),
                    Paragraph(h.get("ip_classification", "unknown").capitalize(), body_style),
                    Paragraph(loc, body_style),
                    Paragraph(f"{h.get('isp', 'Unknown')[:20]}<br/>{h.get('asn', '')}", body_style),
                ])
            h_table = Table(hop_rows, colWidths=[35, 175, 65, 120, 137])
            h_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]))
            story.append(h_table)
            story.append(Spacer(1, 12))

        # 7. URLs & Attachments Table
        if urls or attachments:
            story.append(Paragraph("6. Indicators of Compromise: URLs & Attachments", h2_style))
            if urls:
                url_rows = [[Paragraph("<b>Extracted URL</b>", body_style), Paragraph("<b>Risk</b>", body_style), Paragraph("<b>Forensic Reason</b>", body_style)]]
                for u in urls[:6]:
                    url_rows.append([
                        Paragraph(u.get("full_url", "")[:65], code_style),
                        Paragraph(f"<b>{u.get('risk_level', 'SAFE')} ({u.get('risk', 0)})</b>", body_style),
                        Paragraph(u.get("reason", "")[:120], body_style),
                    ])
                u_table = Table(url_rows, colWidths=[260, 80, 192])
                u_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]))
                story.append(u_table)
                story.append(Spacer(1, 8))

            if attachments:
                att_rows = [[Paragraph("<b>Filename</b>", body_style), Paragraph("<b>MIME / Ext</b>", body_style), Paragraph("<b>SHA-256 Hash</b>", body_style), Paragraph("<b>Risk</b>", body_style)]]
                for a in attachments:
                    att_rows.append([
                        Paragraph(a.get("filename", ""), body_style),
                        Paragraph(f"{a.get('extension', '')}<br/>{a.get('mime_type', '')}", code_style),
                        Paragraph(a.get("sha256", ""), code_style),
                        Paragraph(f"<b>{a.get('risk_level', 'SAFE')}</b>", body_style),
                    ])
                a_table = Table(att_rows, colWidths=[130, 95, 230, 77])
                a_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ]))
                story.append(a_table)
                story.append(Spacer(1, 12))

        # 8. Disclaimer
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#94a3b8"), spaceBefore=15, spaceAfter=8))
        disclaimer_text = (
            "<b>LEGAL & FORENSIC DISCLAIMER:</b> This automated forensic report was generated by the SIH26106 Threat Detection Engine. "
            "All threat scores and intent classifications represent automated heuristics and machine-assisted signals. "
            "Geolocation data reflects observed intermediate mail relays and may not represent the adversary's actual physical origin due to proxies or VPNs. "
            "Security Operations Center (SOC) analyst validation is required prior to enforcement action."
        )
        story.append(Paragraph(disclaimer_text, ParagraphStyle("Disc", parent=body_style, fontSize=7, leading=9.5, textColor=colors.HexColor("#64748b"))))

        # Build document
        doc.build(story, canvasmaker=NumberedCanvas)
        return buffer.getvalue()

    @staticmethod
    def generate_json_export(investigation_data: Dict[str, Any]) -> str:
        """Serializes full machine-readable JSON forensic package."""
        return json.dumps(investigation_data, indent=2, default=str)
